spring.application.name=SIGCAR
server.port=${PORT:8213}
spring.data.mongodb.uri=mongodb+srv://danimiran8_db_user:Empresariales2026@cluster0.em3qo1e.mongodb.net/SIGCAR?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=SIGCAR
logging.level.org.springframework.security=DEBUG